name: CTA CS19i Bridge
version: "0.1.2"
slug: cta_cs19i_bridge
description: CTA CS19i → MQTT bridge (sensors + Start Heating button) + log tables
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
boot: auto
init: false
homeassistant: true
options:
  host: 10.80.21.11
  port: 8214
  password: "999990"
  poll_interval: 30
  demand_delta_c: 5.0
  mqtt_prefix: cta_cs19i
  log_pages: true
  log_changes_only: false
schema:
  host: str
  port: int
  password: str
  poll_interval: int
  demand_delta_c: float
  mqtt_prefix: str
  log_pages: bool
  log_changes_only: bool
services:
  - mqtt:need
